### ISSUE TITLE
Administration page seems broken

### ISSUE THREAD

**Issue by koliada** [vtsukur/spring-rest-black-market#5]
Being logged in as administrator, I got two errors in dev console:

``` javascript
admin.js:124 Uncaught TypeError: Cannot read property 'forEach' of undefined
```

``` javascript
admin.js:21779 GET http://localhost:8080/ads/search net::ERR_BLOCKED_BY_CLIENT
```

"Sozdat novuyu zayavku" button does not work as well.
Is it me doing smth wrong?
Thanks!

**Comment by vtsukur** [comment]
Thanks!

@my8bit can you comment on the issues please?

**Comment by my8bit** [comment]
Sure! 
@koliada The issue is that your AdBlock automatically blocking the URL that contains word _ads_
Add the rule for this URL _http://localhost:8080/ads/search_ into AdBlock exceptions.

**Comment by koliada** [comment]
@my8bit Thanks, will try. Do you think this notice should be mentioned in ReadMe?

**Comment by koliada** [comment]
Disabling AdBlock does not fix the first error:

``` javascript
admin.js:124 Uncaught TypeError: Cannot read property 'forEach' of undefined
```

and the button doesn't work.
